name: frozen-lake
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - backcall=0.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cloudpickle=3.0.0
  - contourpy=1.2.0
  - cycler=0.12.1
  - decorator=5.1.1
  - executing=2.0.1
  - farama-notifications=0.0.4
  - fonttools=4.49.0
  - freetype=2.12.1
  - gym=0.21.0
  - gym-toy_text=0.21.0
  - gymnasium=0.28.1
  - importlib-metadata=7.0.1
  - importlib-resources=6.1.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - ipython=8.12.0
  - jax-jumpy=1.0.0
  - jedi=0.19.1
  - kiwisolver=1.4.5
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.26
  - libpng=1.6.42
  - libsqlite=3.45.1
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - munkres=1.1.4
  - ncurses=6.4
  - numpy=1.26.4
  - openjpeg=2.5.0
  - openssl=3.2.1
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pyparsing=3.1.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - readline=8.2
  - scipy=1.12.0
  - setuptools=69.1.0
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zipp=3.17.0
  - zstd=1.5.5
  - pip:
      - pygame==2.5.2
